/// Database persistence for [`NlheProfile`].
///
/// The struct and `CfrBook` impl are generated by [`cfr!`] in `solver.rs`.
/// This module provides PostgreSQL schema, hydration, and row iteration.
#[cfg(feature = "database")]
use super::*;
#[cfg(feature = "database")]
use rbp_mccfr::*;
#[cfg(feature = "database")]
use std::collections::HashMap;
#[cfg(feature = "database")]
use std::sync::OnceLock;

#[cfg(feature = "database")]
impl rbp_database::Schema for NlheProfile {
    fn name() -> &'static str {
        rbp_database::blueprint()
    }

    fn columns() -> &'static [tokio_postgres::types::Type] {
        &[
            tokio_postgres::types::Type::INT8,   // past (subgame path)
            tokio_postgres::types::Type::INT2,   // present (abstraction bucket)
            tokio_postgres::types::Type::INT8,   // choices (available edges)
            tokio_postgres::types::Type::INT2,   // geometry (SPR bucket)
            tokio_postgres::types::Type::INT8,   // edge (action taken)
            tokio_postgres::types::Type::FLOAT4, // weight
            tokio_postgres::types::Type::FLOAT4, // regret
            tokio_postgres::types::Type::FLOAT4, // payoff
            tokio_postgres::types::Type::INT4,   // visits
        ]
    }

    fn copy() -> &'static str {
        static SQL: OnceLock<&str> = OnceLock::<&str>::new();
        *SQL.get_or_init(|| rbp_database::leaked(format!(
            "COPY {} (past, present, choices, geometry, edge, weight, regret, payoff, visits) FROM STDIN BINARY",
            rbp_database::blueprint()
        )))
    }

    fn creates() -> &'static str {
        static SQL: OnceLock<&str> = OnceLock::<&str>::new();
        *SQL.get_or_init(|| {
            rbp_database::leaked(format!(
                "CREATE TABLE IF NOT EXISTS {} (
                edge       BIGINT,
                past       BIGINT,
                present    SMALLINT,
                choices    BIGINT,
                geometry   SMALLINT,
                weight     REAL,
                regret     REAL,
                payoff     REAL,
                visits     INT DEFAULT 0,
                UNIQUE     (past, present, choices, geometry, edge)
            );",
                rbp_database::blueprint()
            ))
        })
    }

    fn indices() -> &'static str {
        static SQL: OnceLock<&str> = OnceLock::<&str>::new();
        let t = rbp_database::blueprint();
        *SQL.get_or_init(|| rbp_database::leaked(format!(
            "CREATE UNIQUE INDEX IF NOT EXISTS idx_{t}_upsert  ON {t} (present, past, choices, geometry, edge);
             CREATE        INDEX IF NOT EXISTS idx_{t}_bucket  ON {t} (present, past, choices, geometry);
             CREATE        INDEX IF NOT EXISTS idx_{t}_present ON {t} (present);
             CREATE        INDEX IF NOT EXISTS idx_{t}_edge    ON {t} (edge);
             CREATE        INDEX IF NOT EXISTS idx_{t}_past    ON {t} (past);"
        )))
    }

    fn truncates() -> &'static str {
        static SQL: OnceLock<&str> = OnceLock::<&str>::new();
        *SQL.get_or_init(|| {
            rbp_database::leaked(format!("TRUNCATE TABLE {};", rbp_database::blueprint()))
        })
    }

    fn freeze() -> &'static str {
        static SQL: OnceLock<&str> = OnceLock::<&str>::new();
        let t = rbp_database::blueprint();
        *SQL.get_or_init(|| {
            rbp_database::leaked(format!(
                "ALTER TABLE {t} SET (fillfactor = 100);
             ALTER TABLE {t} SET (autovacuum_enabled = false);"
            ))
        })
    }
}

#[cfg(feature = "database")]
#[async_trait::async_trait]
impl rbp_database::Hydrate for NlheProfile {
    async fn hydrate(client: std::sync::Arc<tokio_postgres::Client>) -> Self {
        tracing::info!("{:<32}{:<32}", "loading blueprint", "from database");
        let epoch_sql = format!(
            "SELECT value FROM {} WHERE key = 'current'",
            rbp_database::epoch()
        );
        let epochs = client
            .query_opt(&epoch_sql, &[])
            .await
            .ok()
            .flatten()
            .map(|r| r.get::<_, i64>(0) as usize)
            .expect("to have already created epoch metadata");
        let blueprint_sql = format!(
            "SELECT past, present, choices, geometry, edge, weight, regret, payoff, visits FROM {}",
            rbp_database::blueprint()
        );
        let mut encounters = HashMap::new();
        for row in client
            .query(&blueprint_sql, &[])
            .await
            .expect("to have already created blueprint")
        {
            let subgame = rbp_gameplay::Path::from(row.get::<_, i64>(0) as u64);
            let present = rbp_gameplay::Abstraction::from(row.get::<_, i16>(1));
            let choices = rbp_gameplay::Path::from(row.get::<_, i64>(2) as u64);
            let geometry = Geometry::from(row.get::<_, i16>(3) as u8);
            let edge = NlheEdge::from(row.get::<_, i64>(4) as u64);
            let weight = row.get::<_, f32>(5);
            let regret = row.get::<_, f32>(6);
            let payoff = row.get::<_, f32>(7);
            let visits = row.get::<_, i32>(8) as u32;
            let bucket = NlheInfo::from((subgame, present, choices, geometry));
            encounters
                .entry(bucket)
                .or_insert_with(HashMap::default)
                .entry(edge)
                .or_insert(Encounter::new(weight, regret, payoff, visits));
        }
        tracing::info!(
            "{:<32}{:<32}",
            format!("{} infos", encounters.len()),
            "from database"
        );
        tracing::info!("{:<32}{:<32}", format!("{} iters", epochs), "from database");
        Self {
            epochs,
            encounters,
            metrics: Metrics::with_epoch(epochs),
        }
    }
}

#[cfg(feature = "database")]
impl NlheProfile {
    pub fn rows(
        &self,
    ) -> impl Iterator<Item = (i64, i16, i64, i16, i64, f32, f32, f32, i32)> + '_ {
        self.encounters.iter().flat_map(|(info, edges)| {
            let present = i16::from(info.bucket());
            let subgame = i64::from(info.subgame());
            let choices = i64::from(info.choices());
            let geometry = info.geometry().tag() as i16;
            edges.iter().map(move |(edge, encounter)| {
                (
                    subgame,
                    present,
                    choices,
                    geometry,
                    u64::from(*edge) as i64,
                    encounter.weight,
                    encounter.regret,
                    encounter.payoff,
                    encounter.visits as i32,
                )
            })
        })
    }
}
