//! Hyperparameters for MCCFR training, sampling, pruning, and regret biasing.
//!
//! These types own the algorithm tuning knobs.
//!
//! [`BiasHyperParams`] lives in `croupier` (read by `Edge::regret`)
//! and is re-exported here for downstream convenience. Single source of
//! truth: the `BiasHyperParams` OnceLock generated by `#[derive(HyperParams)]`,
//! read via `BiasHyperParams::get()`.

mod pruning;
mod sampling;
mod training;
mod warmstart;

pub use pruning::*;
pub use sampling::*;
pub use training::*;
pub use warmstart::*;

pub use croupier::BiasHyperParams;
